# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_serializable}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Birkir A. Barkarson"]
  s.date = %q{2011-09-21}
  s.description = %q{Easy versioning of serialization methods}
  s.email = %q{birkirb@stoicviking.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "acts_as_serializable.gemspec",
    "init.rb",
    "lib/acts_as_serializable.rb",
    "lib/serializable/version.rb",
    "lib/serializable/versions.rb",
    "lib/serializable/xbuilder.rb",
    "spec/acts_as_serializable_spec.rb",
    "spec/app/serializations/test_rails_model/version_1_0_0.rb",
    "spec/app/serializations/test_rails_model/version_1_5.rb",
    "spec/app/serializations/test_rails_model/version_2_1.rb",
    "spec/serializations/test_model/version_1_0_0.rb",
    "spec/serializations/test_model/version_1_5.rb",
    "spec/serializations/test_model/version_2_1.rb",
    "spec/spec_helper.rb",
    "spec/version_spec.rb",
    "spec/versions_spec.rb"
  ]
  s.homepage = %q{http://github.com/birkirb/acts_as_serializable}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{serializable}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Easy versioning of serialization methods}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, ["<= 2.1.2"])
      s.add_runtime_dependency(%q<jsonbuilder>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 1.2"])
    else
      s.add_dependency(%q<builder>, ["<= 2.1.2"])
      s.add_dependency(%q<jsonbuilder>, [">= 0.1.0"])
      s.add_dependency(%q<activesupport>, [">= 1.2"])
    end
  else
    s.add_dependency(%q<builder>, ["<= 2.1.2"])
    s.add_dependency(%q<jsonbuilder>, [">= 0.1.0"])
    s.add_dependency(%q<activesupport>, [">= 1.2"])
  end
end

